; Reaction Mixing Desk application settings
[SoundEngine]
asio_device_name = "VB-Matrix VASIO-512"
channelstrip_plugin_path = "C:\Program Files\Common Files\VST3\SSL Native Channel Strip 2.vst3"
meter_plugin_path = "C:\Program Files\Common Files\VST3\SSL Meter Pro.vst3"

[Wwise]
wwise_version = ""
wwise_project_path = ""
wwise_authoring_ip = ""
wwise_authoring_port = 8080

[ControlSurface]
control_surface_midi_in = "SSL V-MIDI Port"
control_surface_midi_out = "SSL V-MIDI Port"

[ScribbleStrip_Wwise]
bus_0 = ""
bus_1 = ""
bus_2 = ""
bus_3 = ""
bus_4 = ""
bus_5 = ""
bus_6 = ""
bus_7 = ""
bus_8 = ""
bus_9 = ""
bus_10 = ""
bus_11 = ""
bus_12 = ""
bus_13 = ""
bus_14 = ""
bus_15 = ""
bus_16 = ""
bus_17 = ""
bus_18 = ""
bus_19 = ""
bus_20 = ""
bus_21 = ""
bus_22 = ""
bus_23 = ""
bus_24 = ""
bus_25 = ""
bus_26 = ""
bus_27 = ""
bus_28 = ""
bus_29 = ""
bus_30 = ""
bus_31 = ""
bus_32 = ""
bus_33 = ""
bus_34 = ""
bus_35 = ""
bus_36 = ""
bus_37 = ""
bus_38 = ""
bus_39 = ""

[ScribbleStrip_MixingDesk]
channel_0 = "Stereo Pair 1"
channel_1 = "Stereo Pair 3"
channel_2 = "Stereo Pair 5"
channel_3 = "Stereo Pair 7"
channel_4 = "Stereo Pair 9"
channel_5 = "Stereo Pair 11"
channel_6 = "Stereo Pair 13"
channel_7 = "Stereo Pair 15"
channel_8 = "Stereo Pair 17"
channel_9 = "Stereo Pair 19"
channel_10 = "Stereo Pair 21"
channel_11 = "Stereo Pair 23"
channel_12 = "Stereo Pair 25"
channel_13 = "Stereo Pair 27"
channel_14 = "Stereo Pair 29"
channel_15 = "Stereo Pair 31"
channel_16 = "Stereo Pair 33"
channel_17 = "Stereo Pair 35"
channel_18 = "Stereo Pair 37"
channel_19 = "Stereo Pair 39"
channel_20 = "Stereo Pair 41"
channel_21 = "Stereo Pair 43"
channel_22 = "Stereo Pair 45"
channel_23 = "Stereo Pair 47"
channel_24 = "Stereo Pair 49"
channel_25 = "Stereo Pair 51"
channel_26 = "Stereo Pair 53"
channel_27 = "Stereo Pair 55"
channel_28 = "Stereo Pair 57"
channel_29 = "Stereo Pair 59"
channel_30 = "Stereo Pair 61"
channel_31 = "Stereo Pair 63"
channel_32 = "Stereo Pair 65"
channel_33 = "Stereo Pair 67"
channel_34 = "Stereo Pair 69"
channel_35 = "Stereo Pair 71"
channel_36 = "Stereo Pair 73"
channel_37 = "Stereo Pair 75"
channel_38 = "Stereo Pair 77"
channel_39 = "Stereo Pair 79"
channel_40 = "Stereo Pair 81"
channel_41 = "Stereo Pair 83"
channel_42 = "Stereo Pair 85"
channel_43 = "Stereo Pair 87"
channel_44 = "Stereo Pair 89"
channel_45 = "Stereo Pair 91"
channel_46 = "Stereo Pair 93"
channel_47 = "Stereo Pair 95"
channel_48 = "Stereo Pair 97"
channel_49 = "Stereo Pair 99"
channel_50 = "Stereo Pair 101"
channel_51 = "Stereo Pair 103"
channel_52 = "Stereo Pair 105"
channel_53 = "Stereo Pair 107"
channel_54 = "Stereo Pair 109"
channel_55 = "Stereo Pair 111"
channel_56 = "Stereo Pair 113"
channel_57 = "Stereo Pair 115"
channel_58 = "Stereo Pair 117"
channel_59 = "Stereo Pair 119"
channel_60 = "Stereo Pair 121"
channel_61 = "Stereo Pair 123"
channel_62 = "Stereo Pair 125"
channel_63 = "Stereo Pair 127"
channel_64 = "Stereo Pair 129"
channel_65 = "Stereo Pair 131"
channel_66 = "Stereo Pair 133"
channel_67 = "Stereo Pair 135"
channel_68 = "Stereo Pair 137"
channel_69 = "Stereo Pair 139"
channel_70 = "Stereo Pair 141"
channel_71 = "Stereo Pair 143"
channel_72 = "Stereo Pair 145"
channel_73 = "Stereo Pair 147"
channel_74 = "Stereo Pair 149"
channel_75 = "Stereo Pair 151"
channel_76 = "Stereo Pair 153"
channel_77 = "Stereo Pair 155"
channel_78 = "Stereo Pair 157"
channel_79 = "Stereo Pair 159"
channel_80 = "Stereo Pair 161"
channel_81 = "Stereo Pair 163"
channel_82 = "Stereo Pair 165"
channel_83 = "Stereo Pair 167"
channel_84 = "Stereo Pair 169"
channel_85 = "Stereo Pair 171"
channel_86 = "Stereo Pair 173"
channel_87 = "Stereo Pair 175"
channel_88 = "Stereo Pair 177"
channel_89 = "Stereo Pair 179"
channel_90 = "Stereo Pair 181"
channel_91 = "Stereo Pair 183"
channel_92 = "Stereo Pair 185"
channel_93 = "Stereo Pair 187"
channel_94 = "Stereo Pair 189"
channel_95 = "Stereo Pair 191"
channel_96 = "Stereo Pair 193"
channel_97 = "Stereo Pair 195"
channel_98 = "Stereo Pair 197"
channel_99 = "Stereo Pair 199"
channel_100 = "Stereo Pair 201"
channel_101 = "Stereo Pair 203"
channel_102 = "Stereo Pair 205"
channel_103 = "Stereo Pair 207"
channel_104 = "Stereo Pair 209"
channel_105 = "Stereo Pair 211"
channel_106 = "Stereo Pair 213"
channel_107 = "Stereo Pair 215"
channel_108 = "Stereo Pair 217"
channel_109 = "Stereo Pair 219"
channel_110 = "Stereo Pair 221"
channel_111 = "Stereo Pair 223"
channel_112 = "Stereo Pair 225"
channel_113 = "Stereo Pair 227"
channel_114 = "Stereo Pair 229"
channel_115 = "Stereo Pair 231"
channel_116 = "Stereo Pair 233"
channel_117 = "Stereo Pair 235"
channel_118 = "Stereo Pair 237"
channel_119 = "Stereo Pair 239"
channel_120 = "Stereo Pair 241"
channel_121 = "Stereo Pair 243"
channel_122 = "Stereo Pair 245"
channel_123 = "Stereo Pair 247"
channel_124 = "Stereo Pair 249"
channel_125 = "Stereo Pair 251"
channel_126 = "Stereo Pair 253"
channel_127 = "Stereo Pair 255"
channel_128 = "Stereo Pair 257"
channel_129 = "Stereo Pair 259"
channel_130 = "Stereo Pair 261"
channel_131 = "Stereo Pair 263"
channel_132 = "Stereo Pair 265"
channel_133 = "Stereo Pair 267"
channel_134 = "Stereo Pair 269"
channel_135 = "Stereo Pair 271"
channel_136 = "Stereo Pair 273"
channel_137 = "Stereo Pair 275"
channel_138 = "Stereo Pair 277"
channel_139 = "Stereo Pair 279"
channel_140 = "Stereo Pair 281"
channel_141 = "Stereo Pair 283"
channel_142 = "Stereo Pair 285"
channel_143 = "Stereo Pair 287"
channel_144 = "Stereo Pair 289"
channel_145 = "Stereo Pair 291"
channel_146 = "Stereo Pair 293"
channel_147 = "Stereo Pair 295"
channel_148 = "Stereo Pair 297"
channel_149 = "Stereo Pair 299"
channel_150 = "Stereo Pair 301"
channel_151 = "Stereo Pair 303"
channel_152 = "Stereo Pair 305"
channel_153 = "Stereo Pair 307"
channel_154 = "Stereo Pair 309"
channel_155 = "Stereo Pair 311"
channel_156 = "Stereo Pair 313"
channel_157 = "Stereo Pair 315"
channel_158 = "Stereo Pair 317"
channel_159 = "Stereo Pair 319"
channel_160 = "Stereo Pair 321"
channel_161 = "Stereo Pair 323"
channel_162 = "Stereo Pair 325"
channel_163 = "Stereo Pair 327"
channel_164 = "Stereo Pair 329"
channel_165 = "Stereo Pair 331"
channel_166 = "Stereo Pair 333"
channel_167 = "Stereo Pair 335"
channel_168 = "Stereo Pair 337"
channel_169 = "Stereo Pair 339"
channel_170 = "Stereo Pair 341"
channel_171 = "Stereo Pair 343"
channel_172 = "Stereo Pair 345"
channel_173 = "Stereo Pair 347"
channel_174 = "Stereo Pair 349"
channel_175 = "Stereo Pair 351"
channel_176 = "Stereo Pair 353"
channel_177 = "Stereo Pair 355"
channel_178 = "Stereo Pair 357"
channel_179 = "Stereo Pair 359"
channel_180 = "Stereo Pair 361"
channel_181 = "Stereo Pair 363"
channel_182 = "Stereo Pair 365"
channel_183 = "Stereo Pair 367"
channel_184 = "Stereo Pair 369"
channel_185 = "Stereo Pair 371"
channel_186 = "Stereo Pair 373"
channel_187 = "Stereo Pair 375"
channel_188 = "Stereo Pair 377"
channel_189 = "Stereo Pair 379"
channel_190 = "Stereo Pair 381"
channel_191 = "Stereo Pair 383"
channel_192 = "Stereo Pair 385"
channel_193 = "Stereo Pair 387"
channel_194 = "Stereo Pair 389"
channel_195 = "Stereo Pair 391"
channel_196 = "Stereo Pair 393"
channel_197 = "Stereo Pair 395"
channel_198 = "Stereo Pair 397"
channel_199 = "Stereo Pair 399"
channel_200 = "Stereo Pair 401"
channel_201 = "Stereo Pair 403"
channel_202 = "Stereo Pair 405"
channel_203 = "Stereo Pair 407"
channel_204 = "Stereo Pair 409"
channel_205 = "Stereo Pair 411"
channel_206 = "Stereo Pair 413"
channel_207 = "Stereo Pair 415"
channel_208 = "Stereo Pair 417"
channel_209 = "Stereo Pair 419"
channel_210 = "Stereo Pair 421"
channel_211 = "Stereo Pair 423"
channel_212 = "Stereo Pair 425"
channel_213 = "Stereo Pair 427"
channel_214 = "Stereo Pair 429"
channel_215 = "Stereo Pair 431"
channel_216 = "Stereo Pair 433"
channel_217 = "Stereo Pair 435"
channel_218 = "Stereo Pair 437"
channel_219 = "Stereo Pair 439"
channel_220 = "Stereo Pair 441"
channel_221 = "Stereo Pair 443"
channel_222 = "Stereo Pair 445"
channel_223 = "Stereo Pair 447"
channel_224 = "Stereo Pair 449"
channel_225 = "Stereo Pair 451"
channel_226 = "Stereo Pair 453"
channel_227 = "Stereo Pair 455"
channel_228 = "Stereo Pair 457"
channel_229 = "Stereo Pair 459"
channel_230 = "Stereo Pair 461"
channel_231 = "Stereo Pair 463"
channel_232 = "Stereo Pair 465"
channel_233 = "Stereo Pair 467"
channel_234 = "Stereo Pair 469"
channel_235 = "Stereo Pair 471"
channel_236 = "Stereo Pair 473"
channel_237 = "Stereo Pair 475"
channel_238 = "Stereo Pair 477"
channel_239 = "Stereo Pair 479"
channel_240 = "Stereo Pair 481"
channel_241 = "Stereo Pair 483"
channel_242 = "Stereo Pair 485"
channel_243 = "Stereo Pair 487"
channel_244 = "Stereo Pair 489"
channel_245 = "Stereo Pair 491"
channel_246 = "Stereo Pair 493"
channel_247 = "Stereo Pair 495"
channel_248 = "Stereo Pair 497"
channel_249 = "Stereo Pair 499"
channel_250 = "Stereo Pair 501"
channel_251 = "Stereo Pair 503"
channel_252 = "Stereo Pair 505"
channel_253 = "Stereo Pair 507"
channel_254 = "Stereo Pair 509"
channel_255 = "Stereo Pair 511"

[ScribbleStrip_MixingGroups]


